name: Aprovisionamiento de la Infraestructura
on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'  # Solo se ejecuta cuando hay cambios en la carpeta infra/
env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
jobs:
  terraform:
    name: Terraform Provisioning
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure Terraform CLI Token
      run: echo "credentials \"app.terraform.io\" { token = \"${{ secrets.TF_API_TOKEN }}\" }" > ~/.terraformrc

    - name: Terraform init
      run: terraform init -input=false 
      working-directory: ./infra

    - name: Terraform validate
      run: terraform validate
      working-directory: ./infra

    - name: Terraform plan
      run: terraform plan
      working-directory: ./infra

    - name: Terraform apply
      run: terraform apply -auto-approve
      working-directory: ./infra